services:
  oracle:
    extends:
      file: compose.yaml
      service: oracle

  keycloak:
    extends:
      file: compose.yaml
      service: keycloak

  puppet:
    extends:
      file: compose.yaml
      service: puppet

  workmap:
    extends:
      file: compose.yaml
      service: workmap
    build:
      context: .
      dockerfile: Dockerfile