services:
  oracle:
    extends:
      file: deps.yaml
      service: oracle

  keycloak:
    extends:
      file: deps.yaml
      service: keycloak

  puppet:
    extends:
      file: deps.yaml
      service: puppet

  workmap:
    hostname: workmap
    container_name: workmap
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"