services:
  oracle:
    extends:
      file: deps.yml
      service: oracle

  keycloak:
    extends:
      file: deps.yml
      service: keycloak

  puppet:
    extends:
      file: deps.yml
      service: puppet

  workmap:
    hostname: workmap
    container_name: workmap
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"
    environment:
      ORACLE_DATASOURCE: 'workmap'
      ORACLE_SERVER: 'oracle:1521'
      ORACLE_USER: 'WORKMAP_OWNER'
      ORACLE_PASS: 'password'
      ORACLE_SERVICE: 'xepdb1'
      PUPPET_SHOW_SERVER: 'puppet:3000'
      INTERNAL_SERVER_URL: 'http://workmap:8080'
      TZ: 'America/New_York'