alter session set container = XEPDB1;

--DROP SEQUENCE WORKMAP_OWNER.WORK_MAP_ID;
--DROP SEQUENCE WORKMAP_OWNER.WORK_MAP_TASK_AREA_ID;
--DROP SEQUENCE WORKMAP_OWNER.WORK_MAP_TASK_TYPE_ID;
--DROP SEQUENCE WORKMAP_OWNER.WORK_MAP_TASK_ID;
--DROP SEQUENCE WORKMAP_OWNER.WORK_MAP_PSS_AREA_ID;
--DROP SEQUENCE WORKMAP_OWNER.WORK_MAP_PSS_STATE_ID;
--DROP SEQUENCE WORKMAP_OWNER.WORK_MAP_PSS_ID;

--DROP TABLE WORKMAP_OWNER.WORK_MAP CASCADE CONSTRAINTS PURGE;
--DROP TABLE WORKMAP_OWNER.WORK_MAP_TASK_AREA CASCADE CONSTRAINTS PURGE;
--DROP TABLE WORKMAP_OWNER.WORK_MAP_TASK_TYPE CASCADE CONSTRAINTS PURGE;
--DROP TABLE WORKMAP_OWNER.WORK_MAP_TASK CASCADE CONSTRAINTS PURGE;
--DROP TABLE WORKMAP_OWNER.WORK_MAP_TASK CASCADE CONSTRAINTS PURGE;
--DROP TABLE WORKMAP_OWNER.WORK_MAP_PSS_AREA CASCADE CONSTRAINTS PURGE;
--DROP TABLE WORKMAP_OWNER.WORK_MAP_PSS_STATE CASCADE CONSTRAINTS PURGE;
--DROP TABLE WORKMAP_OWNER.WORK_MAP_PSS CASCADE CONSTRAINTS PURGE;

CREATE SEQUENCE WORKMAP_OWNER.WORK_MAP_ID
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;
CREATE SEQUENCE WORKMAP_OWNER.WORK_MAP_TASK_AREA_ID
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;
CREATE SEQUENCE WORKMAP_OWNER.WORK_MAP_TASK_TYPE_ID
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;
CREATE SEQUENCE WORKMAP_OWNER.WORK_MAP_TASK_ID
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;
CREATE SEQUENCE WORKMAP_OWNER.WORK_MAP_PSS_AREA_ID
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;
CREATE SEQUENCE WORKMAP_OWNER.WORK_MAP_PSS_STATE_ID
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;
CREATE SEQUENCE WORKMAP_OWNER.WORK_MAP_PSS_ID
    START WITH 1
    NOCYCLE
    NOCACHE
    ORDER;

CREATE TABLE WORKMAP_OWNER.WORK_MAP
(
    WORK_MAP_ID          NUMBER(32,0) NOT NULL ,
    YEAR_MONTH_DAY       TIMESTAMP(0) NOT NULL ,
    NOTE                 VARCHAR2(256 CHAR) NULL ,
    LAST_MODIFIED        TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL ,
    CONSTRAINT WORK_MAP_PK PRIMARY KEY (WORK_MAP_ID) ,
    CONSTRAINT WORK_MAP_AK1 UNIQUE (YEAR_MONTH_DAY) ,
    CONSTRAINT WORK_MAP_CK1 CHECK (EXTRACT(HOUR FROM YEAR_MONTH_DAY) = 0 AND EXTRACT(MINUTE FROM YEAR_MONTH_DAY) = 0 AND EXTRACT(SECOND FROM YEAR_MONTH_DAY) = 0)
);

CREATE TABLE WORKMAP_OWNER.WORK_MAP_TASK_AREA
(
    WORK_MAP_TASK_AREA_ID    NUMBER(32,0) NOT NULL ,
    AREA_NAME                VARCHAR2(32 CHAR) NOT NULL ,
    CONSTRAINT WORK_MAP_TASK_AREA_PK PRIMARY KEY (WORK_MAP_TASK_AREA_ID) ,
    CONSTRAINT WORK_MAP_TASK_AREA_AK1 UNIQUE (AREA_NAME)
);

CREATE TABLE WORKMAP_OWNER.WORK_MAP_TASK_TYPE
(
    WORK_MAP_TASK_TYPE_ID    NUMBER(32,0) NOT NULL ,
    TYPE_NAME                VARCHAR2(32 CHAR) NOT NULL ,
    CSS_CLASS_NAME           VARCHAR2(32 CHAR) NOT NULL ,
    ORDER_ID                 NUMBER(32,0) NOT NULL ,
    CONSTRAINT WORK_MAP_TASK_TYPE_PK PRIMARY KEY (WORK_MAP_TASK_TYPE_ID) ,
    CONSTRAINT WORK_MAP_TASK_TYPE_AK1 UNIQUE (TYPE_NAME)
);

CREATE TABLE WORKMAP_OWNER.WORK_MAP_TASK
(
    WORK_MAP_TASK_ID        NUMBER(32,0) NOT NULL ,
    WORK_MAP_ID             NUMBER(32,0) NOT NULL ,
    WORK_MAP_TASK_AREA_ID   NUMBER(32,0) NOT NULL ,
    WORK_MAP_TASK_TYPE_ID   NUMBER(32,0) NULL ,
    MESSAGE                 VARCHAR2(32 CHAR) NULL ,
    UPSTAIRS_YN             CHAR(1 CHAR) DEFAULT 'N' NOT NULL CONSTRAINT WORK_MAP_TASK_CK1 CHECK (UPSTAIRS_YN IN ('Y', 'N')),
        ICON_ONLY_YN            CHAR(1 CHAR) DEFAULT 'N' NOT NULL CONSTRAINT WORK_MAP_TASK_CK2 CHECK (ICON_ONLY_YN IN ('Y', 'N')),
	CONSTRAINT WORK_MAP_TASK_PK PRIMARY KEY (WORK_MAP_TASK_ID) ,
        CONSTRAINT WORK_MAP_TASK_AK1 UNIQUE (WORK_MAP_ID, WORK_MAP_TASK_AREA_ID) ,
        CONSTRAINT WORK_MAP_TASK_FK1 FOREIGN KEY (WORK_MAP_ID) REFERENCES WORK_MAP (WORK_MAP_ID) ON DELETE CASCADE ,
        CONSTRAINT WORK_MAP_TASK_FK2 FOREIGN KEY (WORK_MAP_TASK_AREA_ID) REFERENCES WORK_MAP_TASK_AREA (WORK_MAP_TASK_AREA_ID) ON DELETE CASCADE ,
        CONSTRAINT WORK_MAP_TASK_FK3 FOREIGN KEY (WORK_MAP_TASK_TYPE_ID) REFERENCES WORK_MAP_TASK_TYPE (WORK_MAP_TASK_TYPE_ID) ON DELETE SET NULL
);

CREATE TABLE WORKMAP_OWNER.WORK_MAP_PSS_AREA
(
    WORK_MAP_PSS_AREA_ID     NUMBER(32,0) NOT NULL ,
    AREA_NAME                VARCHAR2(32 CHAR) NOT NULL ,
    CONSTRAINT WORK_MAP_PSS_AREA_PK PRIMARY KEY (WORK_MAP_PSS_AREA_ID) ,
    CONSTRAINT WORK_MAP_PSS_AREA_AK1 UNIQUE (AREA_NAME)
);

CREATE TABLE WORKMAP_OWNER.WORK_MAP_PSS_STATE
(
    WORK_MAP_PSS_STATE_ID    NUMBER(32,0) NOT NULL ,
    STATE_NAME               VARCHAR2(32 CHAR) NOT NULL ,
    CSS_CLASS_NAME           VARCHAR2(32 CHAR) NOT NULL ,
    WEIGHT               NUMBER(32,0) NULL,
    CONSTRAINT WORK_MAP_PSS_STATE_PK PRIMARY KEY (WORK_MAP_PSS_STATE_ID) ,
    CONSTRAINT WORK_MAP_PSS_STATE_AK1 UNIQUE (STATE_NAME)
);

CREATE TABLE WORKMAP_OWNER.WORK_MAP_PSS
(
    WORK_MAP_PSS_ID        NUMBER(32,0) NOT NULL ,
    WORK_MAP_ID            NUMBER(32,0) NOT NULL ,
    WORK_MAP_PSS_AREA_ID   NUMBER(32,0) NOT NULL ,
    WORK_MAP_PSS_STATE_ID  NUMBER(32,0) NULL ,
    CONSTRAINT WORK_MAP_PSS_PK PRIMARY KEY (WORK_MAP_PSS_ID) ,
    CONSTRAINT WORK_MAP_PSS_AK1 UNIQUE (WORK_MAP_ID, WORK_MAP_PSS_AREA_ID) ,
    CONSTRAINT WORK_MAP_PSS_FK1 FOREIGN KEY (WORK_MAP_ID) REFERENCES WORK_MAP (WORK_MAP_ID) ON DELETE CASCADE ,
    CONSTRAINT WORK_MAP_PSS_FK2 FOREIGN KEY (WORK_MAP_PSS_AREA_ID) REFERENCES WORK_MAP_PSS_AREA (WORK_MAP_PSS_AREA_ID) ON DELETE CASCADE ,
    CONSTRAINT WORK_MAP_PSS_FK3 FOREIGN KEY (WORK_MAP_PSS_STATE_ID) REFERENCES WORK_MAP_PSS_STATE (WORK_MAP_PSS_STATE_ID) ON DELETE SET NULL
);


