name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version file
        run: |
          fileVer=`grep "version =" build.gradle | cut -d' ' -f3`
      - name: Verify version match
        if: ${{ fileVer }} != ${{ GITHUB_REF_NAME }}
        run: |
            echo "tag label doesn't match version string in build.gradle"
            echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
            exit 1
      - name: Setup Build
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Build with Gradle
        run: ./gradlew build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: build/lib/workmap.war